name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      # Use tagged manifest for prerelease; latest for stable
      - name: Set manifest URL for channel (stable vs prerelease)
        id: set_manifest
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            echo "manifest_url=https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json" >> $GITHUB_OUTPUT
          else
            echo "manifest_url=https://github.com/${{ github.repository }}/releases/latest/download/module.json" >> $GITHUB_OUTPUT
          fi

      # Update module.json with release values
      - name: Modify Module Manifest With Release-Specific Values
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "module.json"
        env:
          version: ${{ steps.get_version.outputs.version-without-v }}
          manifest: ${{ steps.set_manifest.outputs.manifest_url }}
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/dice-pool-fx.zip

      # --- Package & publish ------------------------------------------------

      - name: Create Module Archive
        run: |
          mkdir -p dist
          if [ -f LICENSE.md ]; then LIC="LICENSE.md"; else LIC="LICENSE"; fi
          zip -r dist/dice-pool-fx.zip \
            module.json README.md "$LIC" CHANGELOG.md \
            scripts/ \
            -x "packs/*/_source/*"

      - uses: release-flow/keep-a-changelog-action@v3
        id: changelog
        with:
          command: query
          version: ${{ steps.get_version.outputs.version-without-v }}

      - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: ${{ github.event.release.draft }}
          prerelease: ${{ github.event.release.prerelease }}
          name: ${{ steps.get_version.outputs.version-without-v }}
          body: ${{ steps.changelog.outputs.release-notes }}
          artifacts: "module.json, dist/dice-pool-fx.zip"

      # Optional: publish to Foundry package hub (add secret first)
      #- name: Publish Module to FoundryVTT Website
      #  id: publish-to-foundry-website
      #  if: ${{ ! github.event.release.prerelease }}
      #  uses: cs96and/FoundryVTT-release-package@v1
      #  with:
      #    package-token: ${{ secrets.FOUNDRY_RELEASE_TOKEN }}
      #    manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json
